M48
; DRILL file {KiCad 7.0.6-0} date 2024 July 02, Tuesday 22:55:59
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-02T22:55:59+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.6693Y-3.7008
X5.6693Y-4.1732
X6.1417Y-3.7008
X6.1417Y-4.1732
T0
M30
